# Generated by Django 4.2.3 on 2024-07-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0002_processedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedImage',
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='extractedtext',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
